grpc:
  connect:
    host: localhost
    port: 8443
  listen:
    port: 8444
daemon:
  log:
    path: /var/log/asyncrqd/asyncrqd.log
    numbers:
    - 1
    - 2
    - 3
    strings:
    - one
    - two
    - three
machine:
  linux:
    path_init_target: /lib/systemd/system/default.target
    path_inittab: /etc/inittab
    path_inittab_default: "id:5:initdefault:"
    displays_path: /tmp/.X11-unix
