grpc:
  connect:
    host: localhost
    port: 8443
  listen:
    port: 8444
daemon:
  log:
    path: /var/log/asyncrqd/asyncrqd.log
    numbers:
    - 1
    - 2
    - 3
    strings:
    - one
    - two
    - three
